### ISSUE TITLE
Feature request: change port, support .webm and .mp4, search database, volume control

### ISSUE THREAD

**Issue by somebelly** [nortonandrews/kikoeru#8]
Hi,

Thanks for your work. I like it in general but I think it will be better if these features can be added :D

- Port:
https://github.com/nortonandrews/kikoeru/blob/c08ed63d9f9c9399931bd83ecaac9d3f7f4c17b6/src/server/index.js#L48
I assume it's `process.env.PORT` but I haven't found where to change it...

- `.webm` and `.mp4`:
https://github.com/nortonandrews/kikoeru/blob/c08ed63d9f9c9399931bd83ecaac9d3f7f4c17b6/src/server/filesystem/utils.js#L22
Here `.webm` and `.mp4` can be added directly.

- Search:
Now all I can do is ctrl+F...

- Volume control:
Well, this can be done by some browser extensions but I think it's better to have one.

Thank you!

**Comment by nortonandrews** [comment]
Hi, thanks for the feedback!

The port is just an environment variable. For example, if you're on Linux or macOS you can do `PORT=1234 npm start` and the app will use port `1234` instead of the default `8888`. For Windows you can use `set PORT=1234&&npm start` on the default CMD, I'm not sure about Powershell.

I've added sound-only support for webm/mp4 files and a search bar for the circles, tags and VAs pages. I'll upload a new release with these changes in a few minutes.

I'll be adding a page to search for works by name whenever I get some free time in the future, but I'm not sure how I feel about the volume control. It's not a feature I'd use, but if you make a pull request I'd gladly take a look at it.

**Comment by nortonandrews** [comment]
Search bar and webm/mp4 support added on the v0.3.0 release.

**Comment by somebelly** [comment]
Thanks a lot!
